# File generated by Workcraft.
.internals g4 g2
.graph
g2_high g2-/1
g2-/1 g2_low
g2_low g2+/2
g2+/2 g2_high
g4_low g4+/1
g4+/1 g4_high
g4_low g4+/2
g2_low g4+/2
g4+/2 g4_high
g4+/2 g2_low
g2_low g2+/1
g2+/1 g2_high
g4_high g4-/1
g2_high g4-/1
g4-/1 g4_low
g4-/1 g2_high
.marking { g4_high g2_high }
.end
